version: 0.2

phases:
  build:
    commands:
      # Build and deploy
      - |
        aws cloudformation create-stack \
        --stack-name "${MODULE_STACK_NAME}" \
        --template-url "${CFN_TEMPLATE_URL}" \
        --capabilities CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND \
        --role-arn "${CLOUDFORMATION_ROLE_ARN}" \
        --parameters \
        ParameterKey="AppUniqueId",ParameterValue="${APP_UNIQUE_ID}" \
        ParameterKey="FleetwiseVehicleVinAttributeName",ParameterValue="${FLEETWISE_VEHICLE_VIN_ATTRIBUTE_NAME}" \
        ParameterKey="TimestreamToS3UnloadIntervalMinutes",ParameterValue="${TIMESTREAM_TO_S3_UNLOAD_INTERVAL_MINUTES}"
